--- 
- hosts: localhost
  connection: local
  tasks:
  - name: Task 1 Create Ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "osaka"
      instance_type: t2.micro
      security_group: default
      region: ap-northeast-3
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"

    loop:
      - {image : "ami-0db6b6e701fbc0603" , name : "instance_1"}
      - {image : "ami-0db6b6e701fbc0603" , name : "instance_2"}
      - {image : "ami-0106c791cdf6b24fb" , name : "instance_3"}